footer:
  tutorial: "https://www.railstutorial.org/"
  author: "https://www.michaelhartl.com/"
contact:
  tutorial_contact: "https://www.railstutorial.org/contact"
help:
  tutorial_help: "http://www.railstutorial.org/help"
  tutorial_book: "http://www.railstutorial.org/book"
home:
  tutorial_rails: "https://www.railstutorial.org/"
  tutorial_ruby_on_rails: "https://rubyonrails.org/"
user:
  name_min: 10
  email_min: 15
  email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  email_max: 250
  password_min: 6
  index:
    items: 2
  gravatar_size: 80
  gravatar_user_size: 50
  gravatar_email: "https://gravatar.com/emails"
  items: 25
  time_expired: 2
micropost:
  content_max: 140
  image_type_in: <%= %w(image/jpeg image/gif image/png) %>
  resize_image: [500,500]
  gravatar_size: 50
image_accept: "image/jpeg,image/gif,image/png"
image_size: 5
gravatar_size_info: 50
item_follow: 30
